man:
	apk add \
		man \
		man-pages \
	&& true

basics:
	apk add \
		bash \
		binutils \
		coreutils \
		curl \
		diffutils \
		dos2unix \
		findutils \
		gawk \
		grep \
		htop \
		jq \
		less \
		lsof \
		make \
		nload \
		pciutils \
		procps \
		rsync \
		sed \
		shadow \
		unzip \
		usbutils \
		util-linux \
		wget \
		which
	&& true

networking:
	apk add \
		arp-scan@testing \
		bind-tools \
		drill \
		fping \
		ipcalc \
		iproute2 \
		iptables \
		iputils \
		lldpd@testing \
		mtr \
		netcat-openbsd \
		nmap \
		nmap-scripts \
		tcpdump \
		whois \
	&& true

editing:
	apk add \
		aspell \
		ctagsio \
		direnv@testing \
		docker \
		docker-compose \
		fd-doc@testing \
		fd-zsh-completion@testing \
		fd@testing \
		fzf \
		fzf-doc \
		fzf-vim \
		fzf-zsh-completion \
		git \
		git-zsh-completion \
		gnupg \
		httpie \
		openssh \
		python3 \
		ripgrep-doc@testing \
		ripgrep-zsh-completion@testing \
		ripgrep@testing \
		rsync-zsh-completion \
		tmux \
		tmux-zsh-completion \
		vim \
		zsh \
		zsh-vcs \
	&& true
