#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Remap keyboard keys for the mac keyboard
#xmodmap ~/.xmodmap

# Read xorg user settings
xrdb -merge ~/.Xresources &

exec i3
