#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

EXITCODE=0
BADWORDS='var_dump|die|todo'
FILES=`git diff --cached --diff-filter=ACMRTUXB --name-only $against --`

for FILE in $FILES ; do
  if [ "${FILE##*.}" = "php" ]; then

    # Run all php files through php -l and grep for `illegal` words

    /usr/bin/php -l "$FILE" > /dev/null
    if [ $? -gt 0 ]; then
      EXITCODE=1
    fi

    /bin/grep -H -i -n -E "${BADWORDS}" $FILE
    if [ $? -eq 0 ]; then
      EXITCODE=1
    fi

  fi
done


if [ $EXITCODE -gt 0 ]; then
  echo
  echo 'Fix the above erros or use:'
  echo ' git commit --no-validate'
  echo
fi

exit $EXITCODE

# vim:set ft=sh ts=2 sw=2
