#!/bin/sh
set -e

ARGS=""

RDP=$(which xfreerdp)

test -x $RDP || exit 1

[[ ! $@ =~ /bpp:[0-9]* ]] && ARGS="${ARGS} /bpp:32"
[[ ! $@ =~ /network:[a-z]* ]] && ARGS="${ARGS} /network:broadband"
ARGS="${ARGS} +clipboard +fonts +aero -wallpaper -grab-keyboard"

if [[ ${#@} == 0 ]]
then
    echo "Usage: rdp [domain/][user@]host[:port] [<rdesktop_options>]" >&2
    return 1
fi

if [[ ! $@ =~ /size:[0-9x]* ]]; then
    WIDTH=$(xrandr | grep \* | tail -1 | awk '{print $1}' | cut -dx -f1)
    HEIGHT=$(($(xrandr | grep \* | tail -1 | awk '{print $1}' | cut -dx -f2)-20))
    ARGS="${ARGS} /size:${WIDTH}x${HEIGHT}"
fi

[[ $1 =~ '/' ]] && DOMAIN=$( echo $1 | sed -re 's/^([a-z0-9_-]+)\/.*$/\1/i' )
[[ $1 =~ '@' ]] && USER=$( echo $1 | sed -re 's/^([a-z0-9_-]+\/)?([a-z0-9_\.-]*)@.*$/\2/i' )
HOST=$( echo $1 | sed -re 's/^(.*\/)?(.*@)?(.*)$/\3/i' )

shift

[[ -n $DOMAIN ]] && ARGS="$ARGS /d:$DOMAIN"
[[ -n $USER ]] && ARGS="$ARGS /u:$USER"
[[ -n $HOST ]] && ARGS="$ARGS /v:$HOST"

ARGS=$( echo $ARGS | sed -re 's/^ (.*)$/\1/' )

echo -e "\n\033[1mStarting RDP with: $RDP $@ $ARGS\033[0m\n"

( exec $(echo $RDP $@ $ARGS) )
return $?
