#!/bin/sh

FILE=$1

# Assert the input file is readable
[ -r "$FILE" ] || exit 1

# Assert tshark is installed
type tshark > /dev/null 2>&1 || exit 1


for stream in $(tshark -r $FILE -T fields -e tcp.stream | sort -n | uniq)
do
    echo "Analyzing TCP stream: $stream"
    tshark -2 -r $FILE -w $FILE.stream.$stream.cap -R "tcp.stream==$stream"
done
