install:
	brew bundle install --verbose
update:
	brew update
cleanup:
	brew cleanup
go:
	go get -u github.com/fzipp/gocyclo
	go get -u github.com/client9/misspell/cmd/misspell
	go get -u golang.org/x/lint/golint
