#!/bin/zsh

export ZSH_DOTDIR="${HOME}/.zsh"
export ZSH_CACHE="${HOME}/.cache/zsh"

if [ ! -d "${ZSH_CACHE}" ]; then
    mkdir -p "${ZSH_CACHE}"
fi

#fpath=(${ZSH}/{functions,completions}(/FN) $fpath)

# Load all of the config files that end in .zsh
for ZSH_CONF in "${ZSH_DOTDIR}"/framework/<00-99>_*.zsh(N); do
    source "${ZSH_CONF}"
done

unset ZSH_DOTDIR ZSH_CACHE ZSH_CONF
